### ISSUE TITLE
Import other Template files

### ISSUE THREAD

**Issue by RayBenefield** [sumbad/template-literals-loader#1]
Just happened to stumble upon this repo as it could potentially meet a need of ours. We'd like to be able to use template-literals as a templating system for front-end designers. The one key thing that would be needed for that is an "import" system for other template files. I haven't had the chance to take a look at the code yet and haven't worked on a webpack plugin before, how difficult do you think this would be? And if you already plan on tackling it soon, then even better. If not I could look into it.

**Comment by sumbad** [comment]
Hi, thanks for your question. This library is a webpack plugin, and uses only with it. You can import any type files with template literals if you use this plugin. To do this you need to change webpack config. For example:
```
...
{
    test: /\.txt?$/,
    loader: "template-literals-loader"
},
...
```
and then in your code:

```
const template = require('./template.txt');
...
```
